Run YAML document formatter (from Red Hat) on GitHub workflows (#815)
* Run YAML document formatter (from Red Hat)

* Re-format with single quote string setting

diff --git a/.github/workflows/performance-test.yaml b/.github/workflows/performance-test.yaml
--- a/.github/workflows/performance-test.yaml
+++ b/.github/workflows/performance-test.yaml
@@ -1,50 +1,50 @@
 name: Test Performance
 
 on:
-    workflow_dispatch:
-        inputs:
-            apiVersion:
-                description: 'API Version'
-                required: true
-                default: 'v1'
-            environment:
-                description: 'Environment'
-                required: true
-                default: 'yt01'
-                type: choice
-                options:
-                - at22
-                - tt02
-                - yt01
-            tag:
-                description: 'tag the performance test'
-                required: true
-                default: 'Performance test'
-                type: string
-            vus:
-                description: 'Number of VUS'
-                required: true
-                default: 1
-                type: number
-            duration:
-                description: 'Duration of test, ie 30s, 1m, 10m'
-                required: true
-                default: 1m
-                type: string
-            parallelism:
-                description: 'Number of parallel test runs'
-                required: true
-                default: 1
-                type: number  
-            testSuitePath:
-                description: 'Path to test suite to run'
-                required: true
-                default: 'test/k6/src/tests/orders_org_no.js'
-                type: choice
-                options:
-                - 'test/k6/src/tests/orders_org_no.js'
-                - 'test/k6/src/tests/orders_email.js'
-                - 'test/k6/src/tests/orders_sms.js'
+  workflow_dispatch:
+    inputs:
+      apiVersion:
+        description: 'API Version'
+        required: true
+        default: 'v1'
+      environment:
+        description: 'Environment'
+        required: true
+        default: 'yt01'
+        type: choice
+        options:
+          - at22
+          - tt02
+          - yt01
+      tag:
+        description: 'tag the performance test'
+        required: true
+        default: 'Performance test'
+        type: string
+      vus:
+        description: 'Number of VUS'
+        required: true
+        default: 1
+        type: number
+      duration:
+        description: 'Duration of test, ie 30s, 1m, 10m'
+        required: true
+        default: 1m
+        type: string
+      parallelism:
+        description: 'Number of parallel test runs'
+        required: true
+        default: 1
+        type: number
+      testSuitePath:
+        description: 'Path to test suite to run'
+        required: true
+        default: 'test/k6/src/tests/orders_org_no.js'
+        type: choice
+        options:
+          - 'test/k6/src/tests/orders_org_no.js'
+          - 'test/k6/src/tests/orders_email.js'
+          - 'test/k6/src/tests/orders_sms.js'
 
 permissions:
   id-token: write
@@ -55,46 +55,46 @@ jobs:
     runs-on: ubuntu-latest
     environment: dev
     steps:
-    - name: Checkout code
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-    - name: OIDC Login to Azure Public Cloud
-      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
-      with:
-        client-id: ${{ secrets.AZURE_CLIENT_ID }}
-        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-        allow-no-subscriptions: true
-    - name: Populate kubeconfig with k6 context
-      id: populate_kubeconfig_with_k6_context
-      shell: bash
-      run: |
-        if ! az aks install-cli; then
-          echo "Failed to install kubectl CLI"
-          exit 1
-        fi
+      - name: Checkout code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: OIDC Login to Azure Public Cloud
+        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          allow-no-subscriptions: true
+      - name: Populate kubeconfig with k6 context
+        id: populate_kubeconfig_with_k6_context
+        shell: bash
+        run: |
+          if ! az aks install-cli; then
+            echo "Failed to install kubectl CLI"
+            exit 1
+          fi
 
-        if ! az aks get-credentials --resource-group k6tests-rg --name k6tests-cluster; then
-          echo "Failed to populate kubeconfig"
-          exit 1
-        fi
+          if ! az aks get-credentials --resource-group k6tests-rg --name k6tests-cluster; then
+            echo "Failed to populate kubeconfig"
+            exit 1
+          fi
 
-        if ! kubelogin convert-kubeconfig -l azurecli; then
-          echo "Failed to convert kubeconfig"
-          exit 1
-        fi
-    - name: Setup k6
-      uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1.1.0
-    - name: Run K6 tests (${{ inputs.testSuitePath }})
-      run: |
-        echo "Running k6 test suite ${{ inputs.testSuitePath }} with ${{ inputs.vus }} VUs for ${{ inputs.duration }} on ${{ inputs.parallelism }} parallelism"
-        k6configName=$(basename "${{ inputs.testSuitePath }}" .js)
-        k6configName="k6-${k6configName}"
-        ./test/k6/src/tests/run-test-in-k8s.sh \
-          -f "${{ inputs.testSuitePath }}" \
-          -c "$k6configName" \
-          -n "$k6configName" \
-          -v "${{ inputs.vus }}" \
-          -d "${{ inputs.duration }}" \
-          -p "${{ inputs.parallelism }}"
-      env:
-        API_ENVIRONMENT: ${{ inputs.environment }}
-        API_VERSION: ${{ inputs.apiVersion }}
+          if ! kubelogin convert-kubeconfig -l azurecli; then
+            echo "Failed to convert kubeconfig"
+            exit 1
+          fi
+      - name: Setup k6
+        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1.1.0
+      - name: Run K6 tests (${{ inputs.testSuitePath }})
+        run: |
+          echo "Running k6 test suite ${{ inputs.testSuitePath }} with ${{ inputs.vus }} VUs for ${{ inputs.duration }} on ${{ inputs.parallelism }} parallelism"
+          k6configName=$(basename "${{ inputs.testSuitePath }}" .js)
+          k6configName="k6-${k6configName}"
+          ./test/k6/src/tests/run-test-in-k8s.sh \
+            -f "${{ inputs.testSuitePath }}" \
+            -c "$k6configName" \
+            -n "$k6configName" \
+            -v "${{ inputs.vus }}" \
+            -d "${{ inputs.duration }}" \
+            -p "${{ inputs.parallelism }}"
+        env:
+          API_ENVIRONMENT: ${{ inputs.environment }}
+          API_VERSION: ${{ inputs.apiVersion }}
